name: Build Android APK

on:
  push:
    branches:
      - main
      - master # Mengantisipasi jika branch utama Anda bernama master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17' # Versi standar industri Android modern

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # Menggunakan versi stabil terbaru

      - name: Get Dependencies
        run: flutter pub get

      - name: Build Runner (Isar Database Generator)
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build APK (Release Mode)
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: UTD_Store_Rifky_Raihan_Release
          path: build/app/outputs/flutter-apk/app-release.apk