name: Build Android APK

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      # DIPERBARUI: Menggunakan checkout versi 4
      - name: Checkout Code
        uses: actions/checkout@v4

      # DIPERBARUI: Menggunakan setup-java versi 4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # MENGUNCI VERSI FLUTTER: Sesuai dengan spesifikasi Anda (3.41.9)
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.9'
          channel: 'stable'

      - name: Get Dependencies
        run: flutter pub get

      - name: Build Runner (Isar Database Generator)
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build APK (Release Mode)
        run: flutter build apk --release

      # DIPERBARUI: Menggunakan upload-artifact versi 4 (Solusi Error)
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: UTD_Store_Rifky_Raihan_Release
          path: build/app/outputs/flutter-apk/app-release.apk